-- mysql
drop table if exists act_ex_noflowtask;
CREATE TABLE act_ex_noflowtask (
	id bigint(20) NOT NULL,
	task_name varchar(255) NOT NULL COMMENT '任务名称',
	assignee varchar(255) NOT NULL COMMENT '承办人',
	pid varchar(64) NULL COMMENT '流程实例id',
	business_key varchar(255) NULL COMMENT '业务key',
	business_info varchar(255) NULL COMMENT '主题',
	business_url varchar(255) NULL COMMENT '跳转路径',
	priority int(11) NULL COMMENT '紧急程度：50 一般，100 紧急，150 特急',
	wo_code varchar(64) NULL COMMENT '工单编码',
	wo_name varchar(64) NULL COMMENT '工单名称',
	start_user varchar(64) NULL COMMENT '发起人标识',
	start_user_name varchar(64) NULL COMMENT '发起人姓名',
	opinion varchar(255) NULL COMMENT '审批意见',
	claim_time datetime(0) comment '签收时间',
	due_date datetime(0) comment '过期时间',
	status_ int(11) DEFAULT 1 not null comment '状态：0 待签收，1 待办，2 已办',
	create_by bigint(20) NOT NULL,
	create_time datetime(0),
	lastmodified_by bigint(20) NOT NULL,
	lastmodified_time datetime(0),
	attribute1 varchar(255) NULL,
	attribute2 varchar(255) NULL,
	attribute3 varchar(255) NULL,
	attribute4 varchar(255) NULL,
	attribute5 varchar(255) NULL,
	attribute6 varchar(255) NULL,
	attribute7 varchar(255) NULL,
	attribute8 varchar(255) NULL,
	attribute9 varchar(255) NULL,
	PRIMARY KEY (id)
);

-- oracle
drop table act_ex_noflowtask;
CREATE TABLE act_ex_noflowtask(
  id      NUMBER(19, 0)    NOT NULL,
  task_name nvarchar2(255) NOT NULL,
	assignee nvarchar2(255) NOT NULL,
	pid nvarchar2(64) NULL,
	business_key nvarchar2(255) NULL,
	business_info nvarchar2(255) NULL,
	business_url varchar2(255) NULL,
	priority NUMBER,
	wo_code varchar2(64) NULL,
	wo_name varchar2(64) NULL,
	start_user nvarchar2(64) NULL,
	start_user_name varchar2(64) NULL,
	opinion varchar2(255) NULL,
	claim_time TIMESTAMP(6),
	due_date TIMESTAMP(6),
	status_ NUMBER default 1,
  attribute1 varchar2(255) NULL,
  attribute2 varchar2(255) NULL,
  attribute3 varchar2(255) NULL,
  attribute4 varchar2(255) NULL,
  attribute5 varchar2(255) NULL,
  attribute6 varchar2(255) NULL,
  attribute7 varchar2(255) NULL,
  attribute8 varchar2(255) NULL,
  attribute9 varchar2(255) NULL,
  create_by            NUMBER(19, 0)    NOT NULL,
  create_time          TIMESTAMP(6)     NOT NULL,
  lastmodified_by      NUMBER(19, 0)    NOT NULL,
  lastmodified_time    TIMESTAMP(6),
  PRIMARY KEY (id)
);